# Base configuration for the OfflineTeacherModel

# --- Data settings ---
data_dir: data/interim
batch_size: 128
num_workers: 2

# --- Model architecture (Paper Spec: 8 layers total) ---
embed_dim: 512
num_layers: 4  # 4 encoder + 4 decoder = 8 total layers
num_heads: 8
max_sequence_length: 256
dropout: 0.1

# --- Training loop ---
max_epochs: 10
learning_rate: 1.0e-5
weight_decay: 0.01
warmup_steps: 100
gradient_clip_val: 0.5
log_every_n_steps: 50

# --- W&B Logging ---
wandb_project: "martydepth"
checkpoint_dir: /work/10539/drewtaylor635/vista/Martydepth/checkpoints 