# Base configuration for the OnlineTransformer model

# --- Data settings ---
data_dir: data/interim
batch_size: 256
num_workers: 8 

# --- Model architecture ---
embed_dim: 512
num_layers: 8
num_heads: 8
max_sequence_length: 512
dropout: 0.1

# --- Training loop ---
learning_rate: 1.0e-3
weight_decay: 0.01
max_epochs: 50
warmup_steps: 1000
gradient_clip_val: 1.0
log_every_n_steps: 1000

# --- W&B Logging ---
wandb_project: "martydepth"
checkpoint_dir: /work/10539/drewtaylor635/vista/Martydepth/checkpoints 